#!/bin/sh
#set -e
#set -o pipefail

<< LICENSE
The MIT License (MIT)

Copyright 2018 - 2019, Autonomous Software.

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
LICENSE

usage()
{
  cat <<- _EOM_
  deploy: compile and push  metronome to a local qtum instance by default,
  overriding auction launch date, price and supply, if specified.

  Todo: define usage here

_EOM_

}

RPC_HOST=http://127.0.0.1
RESTART_HOST=0
RPC_USER=""
RPC_PASS=""
gasLimit=5000000
sender=qYoQMnchVU5kuUrAH8fiihj1AngrCxShoC

# Proceeds
solar deploy ./contracts/Proceeds.sol --force --gasLimit=$gasLimit --qtum_sender=$sender
# Auctions
solar deploy ./contracts/Auctions.sol --force --gasLimit=$gasLimit --qtum_sender=$sender
# AutonomousConverter
solar deploy ./contracts/AutonomousConverter.sol --force --gasLimit=$gasLimit --qtum_sender=$sender
# SmartToken
solar deploy ./contracts/SmartToken.sol --force --gasLimit=$gasLimit --qtum_sender=$sender
# METToken
solar deploy ./contracts/METToken.sol --force --gasLimit=$gasLimit --qtum_sender=$sender
# TokenPorter
solar deploy ./contracts/TokenPorter.sol --force --gasLimit=$gasLimit --qtum_sender=$sender
# Validator
solar deploy ./contracts/Validator.sol --force --gasLimit=$gasLimit --qtum_sender=$sender
