[parity]
chain = "devnet.json"
base_path = "./parity/localnet/etc"
[network]
port = 30301
[rpc]
port = 8555
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8556
#[account]
#password = ["node.pwds"]
#[mining]
#engine_signer = "0x00Aa39d30F0D20FF03a22cCfc30B7EfbFca597C2"
#reseal_on_txs = "none"