[parity]
chain = "devnet.json"
base_path = "./parity/localnet/etc"
[network]
port = 30301
[rpc]
port = 8555
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[websockets]
port = 8556
#[account]
#password = ["node.pwds"]
#[mining]
#engine_signer = "0x00Bd138aBD70e2F00903268F3Db08f2D25677C9e"
#reseal_on_txs = "none"