#!/bin/sh

set -e

case $QTUM_NETWORK in
  local|regtest)
    SELECT_NETWORK=-regtest
    ;;
  test|testnet)
    SELECT_NETWORK=-testnet
    ;;
  main|mainnet)
    SELECT_NETWORK=
    ;;
  *)
    echo "Unknown network: $QTUM_NETWORK"
    exit 1
esac

mkdir -p $QTUM_DATADIR

exec qtumd ${SELECT_NETWORK} \
  -rpcbind=0.0.0.0:3889 -rpcallowip=0.0.0.0/0 \
  -datadir=$QTUM_DATADIR \
  -logevents \
  -rpcuser=$QTUM_RPC_USER -rpcpassword=$QTUM_RPC_PASS \
  -printtoconsole
