

====================================================
             Welcome to Metronome

You're currently running Metronome in a test
environment, locally inside of tmux.

You have an ETH and ETC Metronome, validators
running and a claimer also running, each in 
different tmux windows. 

To list all windows, type C-b w.

To go to the 'next' window in the list type C-b n.

If you want to leave metronome running, but
go back to your shell, type C-b d. 

If you want to kill the session and metronome, 
enter tmux kill-session into any shell prompt. 

Enjoy!

====================================================

