/* Generated by ts-generator ver. 0.0.5 */
/* tslint:disable */

/// <reference types="truffle-typings" />

import * as TruffleContracts from ".";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Auctions"): TruffleContracts.AuctionsContract;
      require(
        name: "AutonomousConverter"
      ): TruffleContracts.AutonomousConverterContract;
      require(name: "ChainLedger"): TruffleContracts.ChainLedgerContract;
      require(name: "ERC20"): TruffleContracts.ERC20Contract;
      require(name: "ITokenPorter"): TruffleContracts.ITokenPorterContract;
      require(name: "METToken"): TruffleContracts.METTokenContract;
      require(name: "Migrations"): TruffleContracts.MigrationsContract;
      require(name: "Mintable"): TruffleContracts.MintableContract;
      require(
        name: "MockContractReceiver"
      ): TruffleContracts.MockContractReceiverContract;
      require(name: "MockFixedMath"): TruffleContracts.MockFixedMathContract;
      require(
        name: "MockFixedSupplyToken"
      ): TruffleContracts.MockFixedSupplyTokenContract;
      require(name: "MockFormula"): TruffleContracts.MockFormulaContract;
      require(name: "Ownable"): TruffleContracts.OwnableContract;
      require(name: "Owned"): TruffleContracts.OwnedContract;
      require(name: "Pricer"): TruffleContracts.PricerContract;
      require(name: "Proceeds"): TruffleContracts.ProceedsContract;
      require(name: "SmartToken"): TruffleContracts.SmartTokenContract;
      require(name: "Token"): TruffleContracts.TokenContract;
      require(name: "TokenLocker"): TruffleContracts.TokenLockerContract;
      require(name: "TokenPorter"): TruffleContracts.TokenPorterContract;
      require(name: "Validator"): TruffleContracts.ValidatorContract;
    }
  }
}
